init the service
piscibus/php-hashtag pull request #1
Opened 2022-12-31 19:25 UTC by mgamal92

| Q             | A                                                                  |
|---------------|--------------------------------------------------------------------|
| Branch?       | main                                              |
| Bug fix?      | yes                                                             |
| New feature?  | yes                  |
| Deprecations? | no  |
| Tickets       | Fix #...            |
| License       | MIT                                                                |

2022-12-31 19:28 UTC, mgamal92 commented
@imdhemy 
My opinion is to use the service like ```Extractor::getHashtags```, not needed to initialize a new object for now. What do you think ?

2023-01-01 10:29 UTC, imdhemy commented
We can allow both dynamic and static calls. Let's stick to:

```php
$extractor = new Extractor();
$hashtags = $extractor->extract($text);
```

And we can also allow static calls through `__callStatic`. This way we can have a testable class and a static facade. I prefer `extract()` over `getHastags()` because it's shorter and we already know we're dealing with hashtags.

2023-01-02 08:45 UTC, imdhemy requested changes

2023-01-02 08:45 UTC, imdhemy commented on tests/ExampleTest.php
> +<?php
It would be better to remove this example.

2023-01-02 08:45 UTC, imdhemy commented on tests/ExtractorTest.php
> +use function PHPUnit\Framework\assertEquals;
To follow Piscibus convention, let's rename `$extractor` into `$sut`. This makes it clear that this is the **s**ervice **u**nder **t**est.

2023-01-02 08:45 UTC, imdhemy commented on tests/Pest.php
> +<?php
Do we need to keep this file?

2023-01-02 08:46 UTC, imdhemy commented on src/Extractor.php
>  class Extractor
Could you please add the `__callStatic()` implementation to allow static calls?

2023-01-02 10:52 UTC, imdhemy commented
@mgamal92 Could you please check the unresolved comments?

2023-01-02 10:54 UTC, mgamal92 commented on src/Extractor.php
>  class Extractor
> Could you please add the `__callStatic()` implementation to allow static calls?

It's done @imdhemy

2023-01-02 10:56 UTC, imdhemy commented on tests/ExampleTest.php
> +<?php
@mgamal92 I meant this

2023-01-02 10:56 UTC, imdhemy commented on tests/ExtractorTest.php
> +use function PHPUnit\Framework\assertEquals;
@mgamal92 and this one

2023-01-02 11:42 UTC, imdhemy commented
@mgamal92 

- https://github.com/piscibus/php-hashtag/pull/1#discussion_r1059891497
- https://github.com/piscibus/php-hashtag/pull/1#discussion_r1059892636

2023-01-02 11:44 UTC, mgamal92 commented
OK. I will check

2023-01-03 12:27 UTC, imdhemy requested changes

2023-01-03 12:27 UTC, imdhemy commented on src/Extractor.php
> +    public static function extract(string $text): array
As per our [discussion](https://github.com/piscibus/php-hashtag/pull/1#issuecomment-1368409282) we need to support both dynamic and static calls. Remove the `static` keyword, please.

2023-01-03 12:27 UTC, imdhemy commented on src/Extractor.php
> +    public static function __callStatic(string $name, array $arguments)
After removing the `static` keyword from the `extract()` method, instantiating a new object will be required.

2023-01-03 22:24 UTC, mgamal92 commented on src/Extractor.php
> +    public static function extract(string $text): array
@imdhemy 
Please take a look at [this](https://github.com/phpstan/phpstan/issues/5782)

2023-01-03 22:24 UTC, mgamal92 commented on src/Extractor.php
> +    public static function __callStatic(string $name, array $arguments)
https://github.com/piscibus/php-hashtag/pull/1#discussion_r1061003019

2023-01-04 05:04 UTC, imdhemy commented on src/Extractor.php
> +    public static function extract(string $text): array
I didn't get the point

2023-01-06 13:53 UTC, mgamal92 commented on src/Extractor.php
> +    public static function extract(string $text): array
@imdhemy if the ```static``` keyword removed from the method, the method won't be called statically.
Also I'm sorry for the above link, it seems confusing and no to the point. Instead take a look to this [answer](https://stackoverflow.com/a/70347602/5810944)

2023-01-07 09:19 UTC, imdhemy commented on src/Extractor.php
> +    public static function extract(string $text): array
Noted

2023-01-07 09:21 UTC, imdhemy approved these changes
Thank you 🙌

2023-01-07 09:22 UTC, merged