Create ci.yml
piscibus/php-hashtag pull request #2
Opened 2022-12-31 19:48 UTC by mgamal92

| Q             | A                                                                  |
|---------------|--------------------------------------------------------------------|
| Branch?       | main                                              |
| Bug fix?      | yes                                                             |
| New feature?  | yes                   |
| Deprecations? | no  |
| Tickets       | Fix #...            |
| License       | MIT                                                                |

2023-01-01 10:31 UTC, imdhemy commented
Let's wait on this until we replace PHPunit with Pest.

2023-01-07 09:25 UTC, imdhemy requested changes

2023-01-07 09:25 UTC, imdhemy commented on .github/workflows/ci.yml
> +  push:
Let's run this workflow on all branches.

2023-01-07 09:25 UTC, imdhemy commented on .github/workflows/ci.yml
> +#
We can uncomment this step now.

2023-01-07 09:32 UTC, mgamal92 commented on .github/workflows/ci.yml
> +  push:
Done

2023-01-07 09:32 UTC, mgamal92 commented on .github/workflows/ci.yml
> +#
Why ?

2023-01-07 09:39 UTC, imdhemy commented on .github/workflows/ci.yml
> +#
To enable tests 😅

2023-01-07 18:28 UTC, imdhemy approved these changes
Thank you 🙌

2023-01-07 18:28 UTC, merged